- :class    : Sodium::Auth
  :family   : crypto_auth
  :constants:
    - BYTES
    - KEYBYTES
  
  :functions: 
    ~      : [ pointer, pointer, ulong_long, pointer, int ]
    :verify: [ pointer, pointer, ulong_long, poi